#!/bin/sh

# https://github.com/just-containers/s6-overlay/issues/522
# https://community.fly.io/t/is-it-possible-to-use-my-own-init/12082/4

# run /init with PID 1, creating a new PID namespace if necessary
if [ "$$" -eq 1 ]; then
    # we already have PID 1
    exec /init "$@"
else
    # exec unshare --fork --pid --mount --mount-proc /init \"$@\"
    # create a new PID namespace
    # shellcheck disable=SC2016
    exec unshare --pid sh -c '
        # set up /proc and start the real init in the background
        unshare --mount --mount-proc /init "$@" &
        child="$!"
        # forward signals to the real init
        trap "kill -INT \$child" INT
        trap "kill -TERM \$child" TERM
        # wait until the real init exits
        # ("wait" returns early on signals; "kill -0" checks if the process exists)
        until wait "$child" || ! kill -0 "$child" 2>/dev/null; do :; done
    ' sh "$@"
fi
